CREATE TABLE products(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    price DECIMAL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);